window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 80
    lines: 24

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Italic
  
  size: 14

scrolling:
  history: 1000

# Colors (Wombat)
colors:
  # Default colors
  primary:
    background: '0x1f1f1f'
    foreground: '0xe5e1d8'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xf7786d'
    green:   '0xbde97c'
    yellow:  '0xefdfac'
    blue:    '0x6ebaf8'
    magenta: '0xef88ff'
    cyan:    '0x90fdf8'
    white:   '0xe5e1d8'

  # Bright colors
  bright:
    black:   '0xb4b4b4'
    red:     '0xf99f92'
    green:   '0xe3f7a1'
    yellow:  '0xf2e9bf'
    blue:    '0xb3d2ff'
    magenta: '0xe5bdff'
    cyan:    '0xc2fefa'
    white:   '0xffffff'

key_bindings:
  # (macOS only)
  - { key: K,        mods: Command,         action: ClearHistory     }
  - { key: K,        mods: Command,         chars: "\x0c"            }
  - { key: F,        mods: Command,         action: ToggleFullscreen }
  - { key: N,        mods: Command,         action: SpawnNewInstance }
  - { key: B,        mods: Command,         chars: "\x02"            }
