# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Source Code Pro
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Source Code Pro
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Source Code Pro
    # Style can be specified to pick a specific face.
    style: Italic
  
  size: 14

scrolling:
  history: 10000

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '#181818'
    foreground: '#d8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#d8d8d8'
    cursor: '#d8d8d8'

  # Normal colors
  normal:
    black:   '#181818'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#d8d8d8'

  # Bright colors
  bright:
    black:   '#585858'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#f8f8f8'
