theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "custom"
command = "layout=$(xset -q | grep LED | awk '{print $10}') && if [[ $layout == '00000000' ]] ; then echo 'US'; elif [[ $layout == '00001000' ]] ; then echo 'RU'; fi"
interval = 1

[[block]]
block = "net"
device = "wlp1s0"
format = "{speed_up} {speed_down} {ssid}"
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total} ({available} free)"
alert_absolute = true
unit = "GB"
alert = 50
warning = 40

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
display_type = "memory"
icons = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
