theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "custom"
command = "layout=$(xset -q | grep LED | awk '{print $10}') && if [[ $layout == '00000000' ]] ; then echo 'US'; elif [[ $layout == '00001000' ]] ; then echo 'RU'; fi"
interval = 1

[[block]]
block = "net"
device = "wlp1s0"
format = "{speed_up} {speed_down} {ssid}"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
